### ISSUE TITLE
没想到这也能开源，哇咔咔，大佬把我华东交大的logo也加一下吧，祝大佬蒸蒸日上

### ISSUE THREAD

**Issue by Aoyia** [lovefc/china_school_badge#14]

**Comment by lovefc** [comment]
好的，后续尽快添加，我比较好奇，为什么今天突然star多了起来，你们在那看到的这个项目？

**Comment by lovefc** [comment]
哦哦，知道了从来看的了，我会尽快更新的

**Comment by fchange** [comment]
大佬，我是从[这里](https://ruanyifeng.com/blog/)来的，希望加个 【江西农业大学】官网：https://www.jxau.edu.cn/

**Comment by lovefc** [comment]
收到了

**Comment by candy4290** [comment]
大佬，可否加个兰州交通大学的，https://www.lzjtu.edu.cn/

**Comment by lovefc** [comment]
以上都已更新
