### ISSUE TITLE
补充天津工业大学校徽

### ISSUE THREAD

**Issue by cshijiel** [lovefc/china_school_badge#17]
![Tiangong_University](https://github.com/lovefc/china_school_badge/assets/8501605/efc0a717-5c0b-497b-88b1-fcc843e8e4f3)

**Comment by cshijiel** [comment]
代码仓库中的版本是比较老的

**Comment by lovefc** [comment]
好的，尽快更新

**Comment by lovefc** [comment]
已经更新了

**Comment by cshijiel** [comment]
![image](https://github.com/lovefc/china_school_badge/assets/8501605/c118b2fc-7cdd-4f42-8848-a0309625fa96)
简称是tgu,tjpu是旧称。辛苦更正，感谢

**Comment by lovefc** [comment]
我知道了
