### ISSUE TITLE
山东第二医科大学（原潍坊医学院）

### ISSUE THREAD

**Issue by Mikachu2333** [lovefc/china_school_badge#41]
svg格式图片见下。
![校徽-红](https://github.com/lovefc/china_school_badge/assets/63829496/98b1f622-91e6-44ac-baa8-e1978dfcc5dd)

**Comment by Mikachu2333** [comment]
不会svg封装字体，手里只有svg……

**Comment by lovefc** [comment]
记下来了，下次一起更新

**Comment by lovefc** [comment]
已更新
