### ISSUE TITLE
玉溪师范学院

### ISSUE THREAD

**Issue by Wangxf2023** [lovefc/china_school_badge#42]
希望作者下次更新能够加入，感谢！
网站：https://www.yxnu.edu.cn
svg如下：
![07770B78709C140DC87A7A8C43B_DDF5E8FF_49805](https://github.com/lovefc/china_school_badge/assets/154866198/390b7151-f1a7-4522-ae78-477765f61000)

**Comment by lovefc** [comment]
收到了，谢谢您的提供

**Comment by lovefc** [comment]
已更新
