### ISSUE TITLE
求杭州医学院校徽logo矢量图

### ISSUE THREAD

**Issue by CykaZH** [lovefc/china_school_badge#44]
我有位图的，但不知道如何处理成矢量图😂
![杭州医学院](https://github.com/lovefc/china_school_badge/assets/128057850/f5ed288a-fce7-466b-890e-1793239065b5)
)

**Comment by lovefc** [comment]
是要加进去吗？我下次一起更新

**Comment by lovefc** [comment]
已更新

**Comment by CykaZH** [comment]
> 已更新

感谢
