### ISSUE TITLE
中国计量大学

### ISSUE THREAD

**Issue by kazutoiris** [lovefc/china_school_badge#47]
目前 `.fc-icon-cjlu` 所示的校徽怀疑是由位图转换而来，字体边缘比较模糊。中国计量大学官网有提供矢量的校徽设计稿，源文件使用 CorelDRAW 设计，现已导出为 PDF 和 SVG 格式。

另外：OpenType 支持 `SVG-in-OpenType` 特性，可以嵌入彩色字体，建议同时支持单色和彩色校徽。

## PDF 格式

[校徽+校名（横版）（白）.pdf](https://github.com/user-attachments/files/16047959/%2B.pdf)
[校徽+校名（横版）（彩）.pdf](https://github.com/user-attachments/files/16047961/%2B.pdf)
[校徽+校名（横版）（黑）.pdf](https://github.com/user-attachments/files/16047963/%2B.pdf)
[校徽+校名（竖版）（白）.pdf](https://github.com/user-attachments/files/16047966/%2B.pdf)
[校徽+校名（竖版）（彩）.pdf](https://github.com/user-attachments/files/16047967/%2B.pdf)
[校徽+校名（竖版）（黑）.pdf](https://github.com/user-attachments/files/16047968/%2B.pdf)
[校徽白.pdf](https://github.com/user-attachments/files/16047970/default.pdf)
[校徽彩.pdf](https://github.com/user-attachments/files/16047971/default.pdf)
[校徽黑.pdf](https://github.com/user-attachments/files/16047973/default.pdf)

## SVG 格式

[校徽+校名（横版）.svg](https://github.com/lovefc/china_school_badge/assets/78157415/614a7e2e-131c-4d2c-9e53-0b5860212288)
[校徽+校名（竖版）.svg](https://github.com/lovefc/china_school_badge/assets/78157415/8356eba8-fbdb-4665-90a9-e870dedbee32)
[校徽白.svg](https://github.com/lovefc/china_school_badge/assets/78157415/125db23c-8953-4d44-bff9-1a52f86c4add)
[校徽彩.svg](https://github.com/lovefc/china_school_badge/assets/78157415/e2802def-0f0a-432c-b882-d42c84bdb10e)
[校徽黑.svg](https://github.com/lovefc/china_school_badge/assets/78157415/b25ed60d-cd2d-481b-be43-befbc8384a85)

**Comment by lovefc** [comment]
感谢提供，下次一起更新

**Comment by lovefc** [comment]
已更新
