### ISSUE TITLE
彩色svg支持

### ISSUE THREAD

**Issue by stepbystepcode** [lovefc/china_school_badge#56]
可以添加对彩色svg的支持吗？黑白的使用场景不太常见。谢谢

**Comment by lovefc** [comment]
你好，这是一个老项目了，字体图标目前都是黑白色的。
svg的话，文件包也会大很多。svg单独文件也不小（图片转svg，体积并不会小很多），除非都是用svg重绘，那是个巨大的工程量，一个人都很难完成。



---原始邮件---
发件人: "Jing ***@***.***&gt;
发送时间: 2024年12月25日(周三) 下午5:44
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [lovefc/china_school_badge] 彩色svg支持 (Issue #56)




 
可以添加对彩色svg的支持吗？黑白的使用场景不太常见。谢谢
