### ISSUE TITLE
USTC的图标有字迹模糊现象

### ISSUE THREAD

**Issue by alpha1958627** [lovefc/china_school_badge#9]
<img width="582" alt="f45ae74bd602cc34ed065fe736ed1a6" src="https://user-images.githubusercontent.com/89231644/210916192-c3278fae-6271-4b62-9eb1-02b2994541da.png">

**Comment by lovefc** [comment]
好，空闲的时候我重新制作一下

**Comment by lovefc** [comment]
已经重新制作了
